version: '3'
services:
    web:
        depends_on:
            - db
            - php
        image: nginx:alpine
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./php:/var/www/html/
        ports:
          - 3000:80
          - 3001:81
        restart: always

    php:
        build:
          context: ./php
        volumes:
          - ./php:/var/www/html/
        restart: always
    db:
      container_name: sqlWong
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
        MYSQL_USER: user
        MYSQL_PASSWORD: 1234
      ports:
        - 9950:3306

